<a href="https://colab.research.google.com/github/OscarAliM/Matematicas_y_Ciencia_de_Datos_2024/blob/main/Fusi%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#Importamos las librerías requeridas
import pandas as pd
registro = pd.read_excel('surveys.xlsx', index_col=0)
registro=registro.rename(columns={"month":"mes","day":"día","year":"año","plot_id":"avistamiento","species_id": "código","sex":"sexo","hindfoot_length":"patitas","weight":"peso"})
registro

           mes  día   año  avistamiento código sexo  patitas  peso
record_id
1            7   16  1977             2     NL    M     32.0   NaN
2            7   16  1977             3     NL    M     33.0   NaN
3            7   16  1977             2     DM    F     37.0   NaN
4            7   16  1977             7     DM    M     36.0   NaN
5            7   16  1977             3     DM    M     35.0   NaN
...        ...  ...   ...           ...    ...  ...      ...   ...
35545       12   31  2002            15     AH  NaN      NaN   NaN
35546       12   31  2002            15     AH  NaN      NaN   NaN
35547       12   31  2002            10     RM    F     15.0  14.0
35548       12   31  2002             7     DO    M     36.0  51.0
35549       12   31  2002             5    NaN  NaN      NaN   NaN

[35549 rows x 8 columns]

In [17]:
registro.columns

Index(['mes', 'día', 'año', 'avistamiento', 'código', 'sexo', 'patitas',
       'peso'],
      dtype='object')

In [16]:
registro.dtypes

mes               int64
día               int64
año               int64
avistamiento      int64
código           object
sexo             object
patitas         float64
peso            float64
dtype: object

In [18]:
registro.shape

(35549, 8)

In [19]:
pd.unique(registro['código'])

array(['NL', 'DM', 'PF', 'PE', 'DS', 'PP', 'SH', 'OT', 'DO', 'OX', 'SS',
       'OL', 'RM', nan, 'SA', 'PM', 'AH', 'DX', 'AB', 'CB', 'CM', 'CQ',
       'RF', 'PC', 'PG', 'PH', 'PU', 'CV', 'UR', 'UP', 'ZL', 'UL', 'CS',
       'SC', 'BA', 'SF', 'RO', 'AS', 'SO', 'PI', 'ST', 'CU', 'SU', 'RX',
       'PB', 'PL', 'PX', 'CT', 'US'], dtype=object)

In [22]:
len(pd.unique(registro['código']))

49

In [28]:
registro['código'].nunique()

48

In [23]:

sitios=pd.unique(registro['avistamiento'])
sitios

array([ 2,  3,  7,  1,  6,  5,  8,  4, 11, 14, 15, 13,  9, 10, 17, 16, 20,
       23, 18, 21, 22, 19, 12, 24])

In [24]:
len(sitios)

24

In [27]:
#Paso alternativo para encontrar la cantidad de datos distintos que tiene una columna
registro['avistamiento'].nunique()

24

In [29]:
registro['peso'].describe()

count    32283.000000
mean        42.672428
std         36.631259
min          4.000000
25%         20.000000
50%         37.000000
75%         48.000000
max        280.000000
Name: peso, dtype: float64

In [30]:
registro.groupby('sexo').mean("peso")

           mes        día          año  avistamiento    patitas       peso
sexo
F     6.587253  15.880943  1990.644997     11.440854  28.836780  42.170555
M     6.396184  16.078799  1990.480401     11.098282  29.709578  42.995379

In [31]:
agrupación1=registro.groupby(['avistamiento','sexo'])
agrupación1.mean("peso")

                        mes        día          año    patitas       peso
avistamiento sexo
1            F     6.597877  15.338443  1990.933962  31.733911  46.311138
             M     6.121461  15.905936  1990.091324  34.302770  55.950560
2            F     6.426804  16.288660  1990.449485  30.161220  52.561845
             M     6.340035  15.440559  1990.756119  30.353760  51.391382
3            F     6.610302  15.993281  1992.013438  23.774044  31.215349
             M     6.277381  16.271429  1992.275000  23.833744  34.163241
4            F     6.447248  15.608945  1990.235092  33.249102  46.818824
             M     6.436893  16.303883  1991.000971  34.097959  48.888119
5            F     6.142315  15.722960  1986.485769  28.921844  40.974806
             M     6.194539  15.703072  1986.817406  29.694794  40.708551
6            F     6.640434  15.947083  1991.579376  26.981322  36.352288
             M     6.043194  15.856021  1990.556283  27.425591  36.867388
7            F     6.385075  15.313433  1991.441791  19.779553  20.006135
             M     6.719870  15.778502  1991.462541  20.536667  21.194719
8            F     6.644048  15.479762  1991.267857  32.187578  45.623011
             M     6.585961  15.427263  1991.686673  33.751059  49.641372
9            F     6.507620  15.309496  1989.303634  35.126092  53.618469
             M     6.369522  14.970120  1990.632470  34.175732  49.519309
10           F     5.588652  16.964539  1989.248227  18.641791  17.094203
             M     5.718310  16.739437  1989.007042  19.567164  19.971223
11           F     6.770073  15.954988  1989.836983  32.029299  43.515075
             M     6.379981  15.799806  1989.856171  32.078014  43.366197
12           F     6.509434  16.305660  1990.266981  30.975124  49.831731
             M     6.304167  16.367500  1990.400833  31.762489  48.909710
13           F     6.815287  15.847134  1990.619427  27.201014  40.524590
             M     6.485313  15.851852  1989.911877  27.893793  40.097754
14           F     6.519041  16.427362  1989.974612  32.973373  47.355491
             M     6.666355  16.336449  1990.587850  32.961802  45.159378
15           F     6.582121  15.787942  1992.523909  21.949891  26.670236
             M     6.193154  17.193154  1990.770171  21.803109  27.523691
16           F     6.369369  16.549550  1991.351351  23.144928  25.810427
             M     6.208791  16.402930  1990.926740  23.480916  23.811321
17           F     6.650224  15.892377  1990.785874  30.918536  48.176201
             M     6.569801  16.183286  1991.331434  32.227634  47.558853
18           F     6.698013  15.960265  1990.536424  26.690341  36.963514
             M     6.610224  16.797125  1988.551118  27.703072  43.546952
19           F     6.701149  15.226054  1993.417625  21.257937  21.978599
             M     6.533563  16.647160  1991.740103  21.071685  20.306878
20           F     6.743077  16.026154  1990.253846  27.069193  52.624406
             M     6.489396  16.375204  1989.243067  27.908451  44.197279
21           F     6.860884  16.307692  1993.878887  22.366554  25.974832
             M     6.671840  16.203991  1992.199557  21.736721  22.772622
22           F     6.651267  15.521610  1990.973174  34.108320  53.647059
             M     6.381872  16.682021  1990.650817  33.359746  54.572531
23           F     6.860606  16.036364  1989.024242  20.051948  20.564417
             M     6.391304  16.077295  1989.961353  19.850000  18.941463
24           F     6.596708  16.393004  1987.485597  26.993377  47.914405
             M     6.360825  16.971134  1988.641237  25.786996  39.321503

In [32]:
len(registro[pd.isnull(registro.peso)])

3266

In [37]:
registro1=registro.copy()
registro1['peso']=registro1['peso'].fillna(42.67)
registro1['peso'].mean()

42.67220512531998

In [39]:
registro_primeras=registro.head(6)
registro_ultimas=registro.tail(5)
registro_ultimas=registro_ultimas.reset_index(drop=True)
ap_vertical=pd.concat([registro_primeras,registro_ultimas],axis=0) #eje 0 es hacia abajo, eje 1 es el de las x
ap_vertical.reset_index()

    index  mes  día   año  avistamiento código sexo  patitas  peso
0       1    7   16  1977             2     NL    M     32.0   NaN
1       2    7   16  1977             3     NL    M     33.0   NaN
2       3    7   16  1977             2     DM    F     37.0   NaN
3       4    7   16  1977             7     DM    M     36.0   NaN
4       5    7   16  1977             3     DM    M     35.0   NaN
5       6    7   16  1977             1     PF    M     14.0   NaN
6       0   12   31  2002            15     AH  NaN      NaN   NaN
7       1   12   31  2002            15     AH  NaN      NaN   NaN
8       2   12   31  2002            10     RM    F     15.0  14.0
9       3   12   31  2002             7     DO    M     36.0  51.0
10      4   12   31  2002             5    NaN  NaN      NaN   NaN

In [40]:
registros = pd.read_excel('surveys.xlsx')
registros.columns

Index(['record_id', 'month', 'day', 'year', 'plot_id', 'species_id', 'sex',
       'hindfoot_length', 'weight'],
      dtype='object')

In [41]:
especies=pd.read_excel('species.xlsx')
especies.columns

Index(['species_id', 'genus', 'species', 'taxa'], dtype='object')

In [42]:
fusion=pd.merge(left=registros, right=especies,
                left_on='species_id',right_on='species_id')
fusion.sample(10)

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa
8860,22432,6,28,1995,11,DM,M,36.0,47.0,Dipodomys,merriami,Rodent
31759,18834,7,12,1991,19,SF,M,26.0,100.0,Sigmodon,fulviventer,Rodent
1273,37,7,17,1977,11,DM,F,35.0,NaN,Dipodomys,merriami,Rodent
26566,10372,5,23,1985,14,OL,F,20.0,35.0,Onychomys,leucogaster,Rodent
13932,13848,1,23,1988,12,PE,F,21.0,24.0,Peromyscus,eremicus,Rodent
33472,32310,7,22,2001,8,PB,F,26.0,27.0,Chaetodipus,baileyi,Rodent
10197,27524,2,1,1998,14,DM,M,35.0,42.0,Dipodomys,merriami,Rodent
30697,12832,5,28,1987,15,AH,NaN,NaN,NaN,Ammospermophilus,harrisi,Rodent
22288,29777,6,13,1999,4,OT,F,20.0,28.0,Onychomys,torridus,Rodent
33052,30983,7,1,2000,24,PB,M,26.0,28.0,Chaetodipus,baileyi,Rodent